# Generated by Django 5.2.17 on 2026-09-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="首页精选"
            ),
        ),
    ]
